// <auto-generated />
using System;
using GestionCabinetMedecin.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionCabinetMedecin.Migrations
{
    [DbContext(typeof(CabinetDbContext))]
    partial class CabinetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionCabinetMedecin.Models.DossierMedical", b =>
                {
                    b.Property<int>("IdDossier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDossier"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDossier");

                    b.HasIndex("IdPatient")
                        .IsUnique();

                    b.ToTable("DossiersMedicaux");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.Medecin", b =>
                {
                    b.Property<int>("IdMedecin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedecin"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMedecin");

                    b.ToTable("Medecins");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.Notification", b =>
                {
                    b.Property<int>("IdNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotification"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateNotification")
                        .HasColumnType("datetime2");

                    b.Property<int>("RendezVousId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNotification");

                    b.HasIndex("RendezVousId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.Ordonnance", b =>
                {
                    b.Property<int>("IdOrdonnance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdonnance"));

                    b.Property<DateTime>("DateOrdonnance")
                        .HasColumnType("datetime2");

                    b.Property<int>("RendezVousId")
                        .HasColumnType("int");

                    b.HasKey("IdOrdonnance");

                    b.HasIndex("RendezVousId")
                        .IsUnique();

                    b.ToTable("Ordonnances");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.Patient", b =>
                {
                    b.Property<int>("IdPatient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPatient"));

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PatientBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPatient");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.RendezVous", b =>
                {
                    b.Property<int>("IdRdv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRdv"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Heure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("SecretaireId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRdv");

                    b.HasIndex("PatientId");

                    b.HasIndex("SecretaireId");

                    b.ToTable("RendezVous");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.Secretaire", b =>
                {
                    b.Property<int>("IdSecretaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSecretaire"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretaireName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretaireSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSecretaire");

                    b.ToTable("Secretaires");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.Traitement", b =>
                {
                    b.Property<int>("IdTraitement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTraitement"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdonnaceId")
                        .HasColumnType("int");

                    b.Property<int>("TypeTraitementId")
                        .HasColumnType("int");

                    b.HasKey("IdTraitement");

                    b.HasIndex("OrdonnaceId");

                    b.HasIndex("TypeTraitementId");

                    b.ToTable("Traitements");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.TypeTraitement", b =>
                {
                    b.Property<int>("IdType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdType"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdType");

                    b.ToTable("TypeTraitements");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.DossierMedical", b =>
                {
                    b.HasOne("GestionCabinetMedecin.Models.Patient", "Patient")
                        .WithOne("DossierMedical")
                        .HasForeignKey("GestionCabinetMedecin.Models.DossierMedical", "IdPatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.Notification", b =>
                {
                    b.HasOne("GestionCabinetMedecin.Models.RendezVous", "RendezVous")
                        .WithMany("Notifications")
                        .HasForeignKey("RendezVousId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.Ordonnance", b =>
                {
                    b.HasOne("GestionCabinetMedecin.Models.RendezVous", "RendezVous")
                        .WithOne("Ordonnace")
                        .HasForeignKey("GestionCabinetMedecin.Models.Ordonnance", "RendezVousId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.RendezVous", b =>
                {
                    b.HasOne("GestionCabinetMedecin.Models.Patient", "Patient")
                        .WithMany("RendezVous")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionCabinetMedecin.Models.Secretaire", "Secretaire")
                        .WithMany("RendezVous")
                        .HasForeignKey("SecretaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Secretaire");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.Traitement", b =>
                {
                    b.HasOne("GestionCabinetMedecin.Models.Ordonnance", "Ordonnance")
                        .WithMany("Traitements")
                        .HasForeignKey("OrdonnaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionCabinetMedecin.Models.TypeTraitement", "TypeTraitement")
                        .WithMany("Traitements")
                        .HasForeignKey("TypeTraitementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordonnance");

                    b.Navigation("TypeTraitement");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.Ordonnance", b =>
                {
                    b.Navigation("Traitements");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.Patient", b =>
                {
                    b.Navigation("DossierMedical");

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.RendezVous", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Ordonnace");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.Secretaire", b =>
                {
                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("GestionCabinetMedecin.Models.TypeTraitement", b =>
                {
                    b.Navigation("Traitements");
                });
#pragma warning restore 612, 618
        }
    }
}
